services:
  rip-tribute:
    image: ghcr.io/macedot/deslogou:latest
    build: ./rip-tribute-app
    ports:
      - "8000:8000"
    volumes:
      - generated:/srv/generated
    restart: unless-stopped

volumes:
  generated:
